### ISSUE TITLE
problematic license for /unuran/src/utils/hooke.c

### ISSUE THREAD

**Issue by umm0** [scipy/unuran#13]
Hi,

while checking the licensing for Scipy I found the following license statement in /unuran/src/utils/hooke.c
```/*  The author of this software is M.G. Johnson.		   */
/*  Permission to use, copy, modify, and distribute this software  */
/*  for any purpose without fee is hereby granted, provided that   */
/*  this entire notice is included in all copies of any software   */
/*  which is or includes a copy or modification of this software   */
/*  and in all copies of the supporting documentation for such	   */
/*  software.  THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT    */
/*  ANY EXPRESS OR IMPLIED WARRANTY.  IN PARTICULAR, NEITHER THE   */
/*  AUTHOR NOR AT&T MAKE ANY REPRESENTATION OR WARRANTY OF ANY	   */
/*  KIND CONCERNING THE MERCHANTABILITY OF THIS SOFTWARE OR ITS    */
/*  FITNESS FOR ANY PARTICULAR PURPOSE. 			   */
```

(cf. https://spdx.org/licenses/dtoa.html)

I think it would be hard to comply with the following obligation:

> "provided that this entire notice is included [...] in all copies of the supporting documentation"

Depending on what one would consider 'supporting documentation', it would be almost impossible to deliver this in practice.

Because of this obligation, I don't think it can be combined under a BSD license.
And since the copyright holder is neither Josef Leydold nor Wolfgang Hoermann I don't see this covered by the rights granted according to https://github.com/scipy/unuran/blob/993f84a70ea4788f85b2343eb6eaef2204e94ec1/license.txt .

Do yo have any insights (e.g. contact to M.G. Johnson) that would allow this to be used under the project BSD license?

Kind regards,
Ummo

**Comment by tupui** [comment]
Please have a look at the license file. We could have a different wording or else on some file, what matters is what is written in the license file. I.e it's a regular BSD.

**Comment by tupui** [comment]
My mistake the file is not listed. Though I am sure it's as usual an omission of some sort as we had plenty of similar issues in the past 😅

**Comment by tupui** [comment]
@tirthasheshpatel Would you mind double checking?

**Comment by tirthasheshpatel** [comment]
> Do yo have any insights (e.g. contact to M.G. Johnson) that would allow this to be used under the project BSD license?

Thanks for bringing this up. Christoph (@chrisb83) and I got the permission to use all the code under the BSD licence by the authors of UNU.RAN. We also have the permission to use the Netlib libaries. So, I think using this under the conditions of the BSD licence should be fine. @chrisb83 Do you think we should ask the UNU.RAN authors again if it's OK to use this?

**Comment by umm0** [comment]
Thank you guys for the fast replies.

The problem I see with this is that the UNU.RAN authors don't seem to hold the copyright for this file, rather the included it from another origin with `minor changes by Josef Leydold` (see line 8 in https://github.com/scipy/unuran/blob/993f84a70ea4788f85b2343eb6eaef2204e94ec1/unuran/src/utils/hooke.c)

I just realized that I screwed up with the Markdown syntax and thus omitted the line with the original copyright holder:  
```
/*  The author of this software is M.G. Johnson.		   */
/*  Permission to use, copy, modify, and distribute this software  */
/*  for any purpose without fee is hereby granted, provided that   */
/*  this entire notice is included in all copies of any software   */
/*  which is or includes a copy or modification of this software   */
/*  and in all copies of the supporting documentation for such	   */
/*  software.  THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT    */
/*  ANY EXPRESS OR IMPLIED WARRANTY.  IN PARTICULAR, NEITHER THE   */
/*  AUTHOR NOR AT&T MAKE ANY REPRESENTATION OR WARRANTY OF ANY	   */
/*  KIND CONCERNING THE MERCHANTABILITY OF THIS SOFTWARE OR ITS    */
/*  FITNESS FOR ANY PARTICULAR PURPOSE. 
```
another statement is in line 17
```
*	12 February 1994	author: Mark G. Johnson 	   */
```

So the UNU.RAN authors don't seem to have the authority to change the license. This could only be changed by Mark G. Johnson.

**Comment by tupui** [comment]
We will look for clarification, thanks @umm0
