### ISSUE TITLE
Problematic license change of upstream source

### ISSUE THREAD

**Issue by tillea** [scipy/unuran#8]
Hi,
since I intend to upgrade the SciPy Debian package and submodules need to be packaged separately I had a packaging view on this code base.  Since I was not happy about the removed build system files I checked the original source code.  When doing so I realised that the original source code files are GPL-2+ containing the following header

     *****************************************************************************
     *                                                                           *
     *   Copyright (c) 2000-2010 Wolfgang Hoermann and Josef Leydold             *
     *   Department of Statistics and Mathematics, WU Wien, Austria              *
     *                                                                           *
     *   This program is free software; you can redistribute it and/or modify    *
     *   it under the terms of the GNU General Public License as published by    *
     *   the Free Software Foundation; either version 2 of the License, or       *
     *   (at your option) any later version.                                     *
     *                                                                           *
     *   This program is distributed in the hope that it will be useful,         *
     *   but WITHOUT ANY WARRANTY; without even the implied warranty of          *
     *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
     *   GNU General Public License for more details.                            *
     *                                                                           *
     *   You should have received a copy of the GNU General Public License       *
     *   along with this program; if not, write to the                           *
     *   Free Software Foundation, Inc.,                                         *
     *   59 Temple Place, Suite 330, Boston, MA 02111-1307, USA                  *
     *                                                                           *
     *****************************************************************************/

All these files are changed in your repository to something like

     *****************************************************************************
     *                                                                           *
     *   Copyright (c) 2000-2022 Wolfgang Hoermann and Josef Leydold             *
     *   Department of Statistics and Mathematics, WU Wien, Austria              *
     *   SPDX-License-Identifier: BSD-3-Clause                                   *
     *                                                                           *
    
     *                                                                           *
     *****************************************************************************/

Simply changing the license from GPL-2+ to BSD-3-Clause is illegal.  Please do not do this.

I also noticed other changes which I do not see any motivation for which makes inspection of the diff unnecessarily hard.  For instance you are doing changes like

     /* #include directive.                                                       */
         
     /**  Public: User Interface (API)                                           **/
    -#include "mvtdr_newset.ch"
    +#include "mvtdr_newset.h"
       
     /**  Private                                                                **/
    -#include "mvtdr_init.ch"
    -#include "mvtdr_sample.ch"
    -#include "mvtdr_debug.ch"
    -#include "mvtdr_info.ch"
    +#include "mvtdr_init.h"
    +#include "mvtdr_sample.h"
    +#include "mvtdr_debug.h"
    +#include "mvtdr_info.h"
         
     /*---------------------------------------------------------------------------*/

which looks somehow unmotivated (even if I admit that .ch named header files are unusual).  Moreover simply keeping the build system files should not harm your workflow but makes alternative builds more easy.

Kind regards, Andreas.

**Comment by rkern** [comment]
UNURAN was explicitly donated to us under the BSD-3-Clause license by the original authors and copyright holders. This donation is documented. Please check our license files before leveling accusations.

https://github.com/scipy/scipy/blob/main/LICENSES_bundled.txt#L249-L252
https://github.com/scipy/unuran/blob/a63d39160e5ecc4402e7ed0e8417f4c3ff9634cb/license.txt

As for the build process, I think we're comfortable with the current setup.

**Comment by tillea** [comment]
Am Thu, Jan 05, 2023 at 10:43:51AM -0800 schrieb Robert Kern:
> UNURAN was explicitly donated to us under the BSD-3-Clause license by the original authors and copyright holders. This donation is documented. Please check our license files before leveling accusations.

Sorry for not checking the license.  IMHO it makes sense to update the version / date for the current version.
